mysql:
    image: connector/azkaban-mysql:v1
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --lower_case_table_names=1
    ports:
        - "3306:3306"
    environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DB}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

executor:
    image: connector/azkaban-exec:v1
    restart: always
    ports:
        - "12321:12321"
    links:
        - mysql
        - manager
    environment:
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - AZKABAN_DB=${MYSQL_DATABASE}
    volumes:
        - "/execlib:/execlib"
        - "/datax:/datax"

webserver:
    image: connector/azkaban-web:v1
    restart: always
    ports:
        - "8081:8081"
    links:
        - executor
        - mysql
    environment:
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - AZKABAN_USER=${AZKABAN_USER}
        - AZKABAN_PASSWORD=${AZKABAN_PASSWORD}
        - AZKABAN_DB=${MYSQL_DATABASE}

manager:
    image: connector/manager:v1
    restart: always
    ports:
        - "7001:7001"
    links:
        - mysql
    environment:
    environment:
        - APP_SID=DEV
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB=${MYSQL_DATABASE}
        - AZKABAN_HOST=webserver
        - AZKABAN_PORT=8081
        - AZKABAN_USER=${AZKABAN_USER}
        - AZKABAN_PASSWORD=${AZKABAN_PASSWORD}
        - AZKABAN_DB=${MYSQL_DATABASE}
        - MANAGER_AZKABAN_HOST=manager
        - CONNECTOR_HOST=manager
        - CONNECTOR_PORT=7001
        - CONNECTOR_TIMEOUT=120
        - SECURITY_ENABLE=false
        - SECURITY_USERNAME=admin
        - SECURITY_PASSWORD=123
        - SETUP_MODE=INIT
    volumes:
        - "/d/data:/file2csv/data"
        - "/d/data/datax:/datax"
