version: '2'

services:
  manager:
    image: connector/manager:v1.0.0
    restart: always
    ports:
        - "7001:7001"
    networks:
        - cn_net
    environment:
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_PORT=${MYSQL_PORT}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB=${MYSQL_DB}
        - AZKABAN_HOST=${AZKABAN_HOST}
        - AZKABAN_PORT=${AZKABAN_PORT}
        - AZKABAN_USER=${AZKABAN_USER}
        - AZKABAN_PASSWORD=${AZKABAN_PASSWORD}
        - AZKABAN_DB=${AZKABAN_DB}
        - MANAGER_HOST=${MANAGER_HOST}
        - MANAGER_PORT=${MANAGER_PORT}
        - SETUP_MODE=${SETUP_MODE}
    volumes:
        - "/d/data:/file2csv/data"
        - "/d/data/datax:/datax"

networks:
    cn_net:
       driver: bridge
